.circleci/config.yml, README.md, package-lock.json, package.json
Starts on #60 (again). Looks like there are some failures still, but this gets it most of the way...
=> Fixed CircleCI build; added README.md badge

src/cli/index.ts, src/index.ts
Fixes #70
Also adds in a nice yellow color!
=> Removed stack trace after 'no fixes specified' complaint

src/options/optionVerification.ts
=> Added error if fixStrictNonNullAssertions is enabled without strictNullChecks

src/mutators/builtIn/callExpressionMutator.ts, src/mutators/builtIn/returnTypes/fixMissingNonNullReturns.ts, src/mutators/collectMutationsFromNodes.ts, src/shared/nodeTypes.ts, src/shared/nodes.ts, test/cases/unit/call expressions/all/expected.ts, test/cases/unit/call expressions/default/expected.ts, test/cases/unit/call expressions/incompleteTypes/expected.ts, test/cases/unit/call expressions/noImplicitAny/expected.ts, test/cases/unit/call expressions/original.ts, test/cases/unit/call expressions/strictNonNullAssertions/expected.ts, test/cases/unit/returns/strictNonNullAssertions/expected.ts
=> Added non null expressions for local variables passed to call expressions

docs/Types.md, src/cli/index.ts, src/index.ts, src/options/addedMutators.ts, src/options/fillOutRawOptions.ts, src/options/loadOptions.ts, src/options/optionVerification.ts, src/shared/maps.ts, src/tests/runTests.ts
Added to docs and filed #82 to add unit tests for this area.
Fixes #46.
=> Added a CLI option for type aliases

src/options/findRawOptions.ts, src/options/loadOptions.ts
=> Used relative tsconfig.json paths from config files

README.md, docs/Files.md, docs/Fixes.md, src/cli/runCli.ts, src/index.ts, src/options/fillOutRawOptions.ts, src/options/parsing/collectFileOptions.ts, src/options/types.ts, src/runtime/collectFilteredNodes.ts, src/runtime/createProviderFromProviders.ts, src/runtime/createTypeStatMutationsProvider.ts, src/runtime/providers/createCoreMutationsProvider.ts, src/runtime/providers/createMarkFilesModifiedProvider.ts, test/cases/files/above/expected.ts, test/cases/files/above/tsconfig.json, test/cases/files/above/typestat.json, test/cases/files/below/expected.ts, test/cases/files/below/tsconfig.json, test/cases/files/below/typestat.json, test/cases/files/both/expected.ts, test/cases/files/both/tsconfig.json, test/cases/files/both/typestat.json, test/cases/files/empty/expected.ts, test/cases/files/empty/tsconfig.json, test/cases/files/empty/typestat.json, test/cases/files/original.ts
=> Added 'above' and 'below' as file options

README.md, docs/Architecture.md, docs/Files.md, src/index.ts, src/options/parsing/collectFileOptions.ts, src/options/types.ts, src/runtime/createTypeStatMutationsProvider.ts, src/runtime/providers/createFileRenameProvider.ts, src/runtime/providers/createMarkFilesModifiedProvider.ts, src/services/createProgramConfiguration.ts, src/services/language.ts
Fixes #90
I don't know how to add tests for this yet. Maybe they should just be unit tests for the provider?
=> Added file extension renaming for .js(x) files

src/options/processFileRenames.ts
=> Added a "Renaming X files..." message

src/mutations/codeFixes/creation.ts, src/mutations/codeFixes/noImplicitAny.ts, test/cases/unit/parameters/all/expected.ts, test/cases/unit/parameters/default/expected.ts, test/cases/unit/parameters/incompleteTypes/expected.ts, test/cases/unit/parameters/noImplicitAny/expected.ts, test/cases/unit/parameters/original.ts, test/cases/unit/parameters/strictNonNullAssertions/expected.ts
=> Stopped adding blank-ish types with --fixNoImplicitAny

src/mutators/builtIn/fixIncompleteTypes/README.md, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactClassProps.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/propTypes/getPropTypesValue.ts, test/cases/unit/class declarations/prop types/all/expected.ts, test/cases/unit/class declarations/prop types/original.ts
=> Fixed for React classes that later assign propTypes

renovate.json
=> Added automerge: true to renovate.json

src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/annotation/createInterfaceUsageMutation.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/index.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/propTypes/createInterfaceFromPropTypes.ts, src/shared/nodes.ts, test/cases/unit/class declarations/prop types/incompleteTypes/expected.ts, test/cases/unit/functional components/arrow functions/incompleteTypes/actual.tsx, test/cases/unit/functional components/arrow functions/incompleteTypes/expected.tsx, test/cases/unit/functional components/function declarations/incompleteTypes/actual.tsx, test/cases/unit/functional components/function declarations/incompleteTypes/expected.tsx, test/cases/unit/functional components/function expressions/incompleteTypes/actual.tsx, test/cases/unit/functional components/function expressions/incompleteTypes/expected.tsx
=> Added React props usage mutations

src/mutations/aliasing.ts, src/mutations/collecting.ts, src/mutations/expansions/addMissingTypesToType.ts, src/mutations/expansions/eliminations.ts, src/mutations/expansions/expansionMutations.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteInterfaceOrTypeLiteralGenerics/collectGenericNodeReferences.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteInterfaceOrTypeLiteralGenerics/expandValuesAssignedToReferenceNodes.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteInterfaceOrTypeLiteralGenerics/index.ts, src/mutators/builtIn/fixIncompleteTypes/index.ts, src/shared/FileInfoCache.ts, src/shared/nodeTypes.ts, src/shared/references.ts, src/shared/typeNodes.ts, test/cases/unit/class declarations/missing props/incompleteTypes/actual.tsx, test/cases/unit/class declarations/missing props/incompleteTypes/expected.tsx, test/cases/unit/generic property declarations/incompleteTypes/expected.ts, test/cases/unit/generic property declarations/incompleteTypes/tsconfig.json, test/cases/unit/generic property declarations/incompleteTypes/typestat.json, test/cases/unit/generic property declarations/original.ts
=> Expanded incompleteTypes property fixes to interface members via generics

src/options/fillOutRawOptions.ts, src/options/types.ts, src/runtime/createTypeStatProvider.ts, src/runtime/providers/createPostProcessingProvider.ts, src/runtime/providers/missingTypes/runCommand.ts, test/cases/post processing/one/incompleteTypes/expected.ts, test/cases/post processing/one/incompleteTypes/tsconfig.json, test/cases/post processing/one/incompleteTypes/typestat.json, test/cases/post processing/one/original.ts, test/cases/post processing/one/postProcess.js
=> Added post-processing command support

src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/propTypes/propTypesTransforms.ts, test/cases/unit/class declarations/prop types/incompleteTypes/expected.ts, test/cases/unit/class declarations/prop types/original.ts
=> Fixed PropTypes.oneOf(Type) to not wrap types in arrays

src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/index.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/propTypes/createInterfaceFromPropTypes.ts, src/shared/fileNames.ts, test/cases/unit/class declarations/prop types generated name from default export/incompleteTypes/expected.ts, test/cases/unit/class declarations/prop types generated name from default export/incompleteTypes/tsconfig.json, test/cases/unit/class declarations/prop types generated name from default export/incompleteTypes/typestat.json, test/cases/unit/class declarations/prop types generated name from default export/original.ts
=> Allowed generated prop type interfaces on default exports to use the file name

src/mutations/aliasing.ts, src/shared/printing/nodePrinting.ts, test/cases/types/aliases/assertions/expected.ts, test/cases/types/aliases/original.ts, test/cases/types/aliases/types/expected.ts
=> Changed type aliasing to print function signatures as lambdas

README.md, bin/typestat
Spiffies up the syntax in bin/typestat to match.
Fixes #261.
=> Clarified Node version requirement as LTS

src/mutations/renames/findRequireRenameMutationsInFile.ts, src/options/processFileRenames.ts, src/runtime/createFileNamesAndServices.ts, src/runtime/findMutationsInFile.ts, src/runtime/providers/createCoreMutationsProvider.ts, src/runtime/providers/createRequireRenameProvider.ts
It's not worth the bug farm...
Fixes #244.
=> Stopped clearing lines from process output

src/shared/references.ts
=> Ignored reference entries from .d.ts files

.circleci/config.yml
=> Parallelized tasks in Circle config

src/initialization/index.ts, src/initialization/initializeJavaScript/index.ts, src/initialization/initializeJavaScript/writeJavaScriptConfig.ts, src/initialization/initializeTypeScript/index.ts, src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts, src/initialization/initializeTypeScript/writeSingleTypeScriptConfig.ts, src/initialization/project/index.ts
=> Added prompt for user's tsconfig.json

src/options/processFileRenames.ts
=> Skipped renaming files that aren't of a .js or .jsx extension

README.md, docs/Development.md, docs/Files.md, docs/Fixes.md, docs/Package.md, docs/Usage.md, docs/Usage/Converting Classes from JavaScript to TypeScript.md, docs/Usage/Enabling Strict Null Checks.md, src/initialization/sources/index.ts
Streamlines the reading experience to better encourage people to use an auto-generated config file. Removes a lot of docs cruft that was confusing or misleading.
Fixes #235. Fixes #237. Fixes #239. Fixes #240.
=> Overhauled README.md and associated high-level docs

src/mutators/builtIn/fixIncompleteTypes/README.md
=> Added missing React docs to incompleteTypes README.md

package.json, tslint.json, yarn.lock
Updates other packages as well.
=> Updated TSLint to 5.20

babel.config.js, package.json, src/cli/index.stubs.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteInterfaceOrTypeLiteralGenerics/collectGenericNodeReferences.ts, yarn.lock
This is what I get for pushing straight to master. 😄
=> Fixed generic node reference mutation tests

src/mutations/codeFixes/noImplicitAny.ts, test/cases/unit/parameters/all/expected.ts, test/cases/unit/parameters/default/expected.ts, test/cases/unit/parameters/incompleteTypes/expected.ts, test/cases/unit/parameters/noImplicitAny/expected.ts, test/cases/unit/parameters/original.ts, test/cases/unit/parameters/strictNonNullAssertions/expected.ts, test/cases/unit/variables/noImplicitAny/expected.ts
=> Stopped inferring types on parameters not of type any

src/services/createProgramConfiguration.ts
=> Added skipLibCheck: true to created programs

src/mutations/expansions/expansionMutations.ts, src/mutations/typeMutating/createNonNullAssertion.ts, src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromLaterAssignments/getComponentAssignedTypesFromUsage.ts, src/mutators/builtIn/fixStrictNonNullAssertions/fixStrictNonNullAssertionCallExpressions/index.ts, src/mutators/builtIn/fixStrictNonNullAssertions/fixStrictNonNullAssertionObjectLiterals/index.ts, src/mutators/builtIn/fixStrictNonNullAssertions/index.ts, src/shared/assignments.ts, src/shared/functionTypes.ts, src/shared/names.ts, src/shared/nodeTypes.ts, src/shared/nodes.ts, test/cases/unit/object literals/inline assertions/original.ts, test/cases/unit/object literals/inline assertions/strictNonNullAssertions/expected.ts, test/cases/unit/object literals/inline assertions/strictNonNullAssertions/tsconfig.json, test/cases/unit/object literals/inline assertions/strictNonNullAssertions/typestat.json
=> Added strict non-null assertion support for object literals

docs/Fixes.md, src/initialization/initializeTypeScript/improvements.ts, src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts, src/mutations/collecting.ts, src/mutations/removals.ts, src/mutators/builtIn/fixNoInferableTypes/README.md, src/mutators/builtIn/fixNoInferableTypes/fixNoInferableTypesParameters/index.ts, src/mutators/builtIn/fixNoInferableTypes/fixNoInferableTypesPropertyDeclarations/index.ts, src/mutators/builtIn/fixNoInferableTypes/fixNoInferableTypesVariableDeclarations/index.ts, src/mutators/builtIn/fixNoInferableTypes/index.ts, src/mutators/builtIn/index.ts, src/mutators/collectMutationsFromNodes.ts, src/options/fillOutRawOptions.ts, src/options/types.ts, src/shared/comparisons.ts, src/shared/nodeTypes.ts, src/shared/typeNodes.ts, test/cases/unit/inferable types/inferable parameters/noInferableTypes/expected.ts, test/cases/unit/inferable types/inferable parameters/noInferableTypes/tsconfig.json, test/cases/unit/inferable types/inferable parameters/noInferableTypes/typestat.json, test/cases/unit/inferable types/inferable parameters/original.ts, test/cases/unit/inferable types/inferable property declarations/noInferableTypes/expected.ts, test/cases/unit/inferable types/inferable property declarations/noInferableTypes/tsconfig.json, test/cases/unit/inferable types/inferable property declarations/noInferableTypes/typestat.json, test/cases/unit/inferable types/inferable property declarations/original.ts, test/cases/unit/inferable types/inferable variable declarations/noInferableTypes/expected.ts, test/cases/unit/inferable types/inferable variable declarations/noInferableTypes/tsconfig.json, test/cases/unit/inferable types/inferable variable declarations/noInferableTypes/typestat.json, test/cases/unit/inferable types/inferable variable declarations/original.ts
=> Added noInferableTypes fixer

src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromLaterAssignments/index.ts, test/cases/unit/functional components/arrow functions/incompleteTypes/expected.tsx, test/cases/unit/functional components/arrow functions/original.tsx
=> Fixed infinitely added inferred React props

package.json, yarn.lock
It's a little smaller now. Good little housekeeping point.
=> Recreated yarn.lock

src/initialization/initializeTypeScript/improvements.ts
Fixes #673.
I didn't see any other missing fixers.
=> Added missing missingProperties fixer to initialization

src/mutators/builtIn/fixIncompleteTypes/README.md
=> Corrected fixIncompleteTypes docs on strict null checks

.github/CODE_OF_CONDUCT.md, .github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> Added GitHub code of conduct, issue templates, and PR template

.circleci/config.yml
Quick lil utility to automate publishes. I still haven't found a Github Action I love, so using this for now...
=> Added npm publish command for main branch

dependabot.yml
-   [x] Addresses an existing issue: fixes #995
=> Use native Dependabot

.eslintrc.js, src/cli/runCli.ts, src/mutations/createExposedTypeScript.ts, src/options/findRawOptions.ts, src/options/loadPendingOptions.ts, src/options/parseRawCompilerOptions.ts, src/runtime/findMutationsInFile.ts, src/services/createProgramConfiguration.ts, src/services/language.ts, src/shared/errors.ts, src/shared/nodeExtensions.ts, src/shared/typeNodes.ts, src/tests/runTests.ts, tsconfig.eslint.json, tsconfig.json
I'm going to eventually have this take in https://github.com/JoshuaKGoldberg/template-typescript-node-package. In the meantime this enables a bunch more linting rules.
=> chore: enabled some more ESLint rules

.github/actions/prepare/action.yml
~~I'm trying to see, will this fix inconsistency between local and CI lint run~~
This just updates the action version. The inconsistency was because of unrelated reason, see #1478
=> fix(deps): update pnpm/action-setup@v3

.github/DEVELOPMENT.md
I think this strikes a good balance of "info that's specific to TypeStat" and "not overexplaining what can be inferred".
💖
=> docs: mention node bin/typestat.mjs

src/initialization/sources/index.ts
There's no issue about this since it's just quick type fix.
=> chore: fix typing in code
