- README.md
- docs/Types.md
- src/mutations/aliasing.ts
- src/mutations/typeMutating/createNonNullAssertion.ts
- src/options/fillOutRawOptions.ts
- src/options/parsing/collectNoImplicitAny.ts
- src/options/parsing/collectStrictNullChecks.ts
- src/options/parsing/collectTypeAliases.ts
- src/options/types.ts
- test/cases/types/aliases/types/expected.ts
- test/cases/types/aliases/types/typestat.json
It's a bit less efficient now that it has to loop through keys each time. I could add a cache but that seems like extra work. Eventually, if performance profiling shows that to be a bad thing, that can happen.
Splits out some pieces of `fillOutRawOptions` into separate files because the one file was getting too big.
Fixes #9.
> Added regexp matching for type alias keys

- src/mutations/typeMutating/createNonNullAssertion.ts
- src/mutators/builtIn/variableDeclarationMutator.ts
- test/cases/unit/variables/all/expected.ts
- test/cases/unit/variables/default/expected.ts
- test/cases/unit/variables/incompleteTypes/expected.ts
- test/cases/unit/variables/incompleteTypesStrict/expected.ts
- test/cases/unit/variables/incompleteTypesStrict/tsconfig.json
- test/cases/unit/variables/incompleteTypesStrict/typestat.json
- test/cases/unit/variables/noImplicitAny/expected.ts
- test/cases/unit/variables/strictNonNullAssertions/expected.ts
- test/cases/unit/variables/strictNullChecks/expected.ts
- test/cases/unit/variables/typeAliases/expected.ts
Noticed a bug in the variable declaration mutator and fixed it & the test cases.
Awaiting seems to throw an error in TypeScript's type checker. Hmm. Will just sit on that.
Fixes #57.
> Added parenthesis wrapping for !s on await expressions

- src/options/addedMutators.ts
- src/options/types.ts
- src/runtime/findMutationsInFile.ts
As @ian-craig noted, it's a little odd to choose between these things within `findMutationsInFile`. The "which mutations will we apply?" logic should really be part of options parsing. The work to look at the raw options for them is already done in `options/addedMutators.ts`, so this tweaks the logic to default to `builtInFileMutators` instead of an empty array.
Starts on #96.
> Moved custom/built-in mutation resolving earlier, to option parsing

- src/mutations/codeFixes/noImplicitAny.ts
TypeScript still provides --noImplicitAny fixes for variables that can't receive them, so catch clauses shouldn't have them.
TypeScript provides all parameters' --noImplicitAny fixes when asked for any parameter, so only request on the first.
Starts on #77.
> Removed unnecessary --noImplicitAny fixes on catch clauses and non-first parameters

- README.md
- src/cli/runCli.ts
- src/options/processFileRenames.ts
Adds a bit more explanation to README.md, and a complaint at runtime if .js files are provided without the option
Fixes #111
> Better docs and .js(x) file handling for --fileRenameExtensions

- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromLaterAssignments/getComponentAssignedTypesFromUsage.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromLaterAssignments/getComponentPropsNode.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromLaterAssignments/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/propTypes/createInterfaceFromPropTypes.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/propTypes/getPropTypesValue.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/reactFiltering/isReactComponentNode.ts
- src/shared/nodes.ts
- test/cases/unit/functional components/arrow functions/incompleteTypes/actual.tsx
- test/cases/unit/functional components/arrow functions/incompleteTypes/expected.tsx
- test/cases/unit/functional components/arrow functions/incompleteTypes/tsconfig.json
- test/cases/unit/functional components/arrow functions/incompleteTypes/typestat.json
- test/cases/unit/functional components/arrow functions/original.tsx
- test/cases/unit/functional components/function declarations/incompleteTypes/actual.tsx
- test/cases/unit/functional components/function declarations/incompleteTypes/expected.tsx
- test/cases/unit/functional components/function declarations/incompleteTypes/tsconfig.json
- test/cases/unit/functional components/function declarations/incompleteTypes/typestat.json
- test/cases/unit/functional components/function declarations/original.tsx
- test/cases/unit/functional components/function expressions/incompleteTypes/actual.tsx
- test/cases/unit/functional components/function expressions/incompleteTypes/expected.tsx
- test/cases/unit/functional components/function expressions/incompleteTypes/tsconfig.json
- test/cases/unit/functional components/function expressions/incompleteTypes/typestat.json
- test/cases/unit/functional components/function expressions/original.tsx
Most of the changes are in test cases and typings. Getting the name or prop types declaration of a node now means checking which form it is & acting appropriately.
Fixes #131.
> Added functional component support to react component logic

- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteImplicitGenerics/index.ts
- test/cases/unit/missing generic property declarations/incompleteTypes/expected.ts
- test/cases/unit/missing generic property declarations/original.ts
We can skip performing any mutation if none of the parameter types discovered in fixIncompleteImplicitGenerics had missing types
> Skipped implicit generic interfaces for no missing types

- src/runtime/providers/createCoreMutationsProvider.ts
- src/shared/NameGenerator.test.ts
- src/shared/NameGenerator.ts
Moves clearing of the services cache to when lastFileIndex is set to 0. I don't know why this would make things work better but it seems that duplicate mutations no longer get applied with this. Spooky.
Fixes #259. Or maybe not. Who knows?
> Simplified core mutations provider resetting

- src/mutations/collecting.ts
- src/mutations/collecting/flags.ts
- test/cases/types/aliases/assertions/expected.ts
- test/cases/types/aliases/original.ts
- test/cases/types/aliases/types/expected.ts
Ignores assigned function types when the declared type(s) include function(s).
Fixes #269.
> Stopped collecting assigned function types from declared function types

- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteParameterTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompletePropertyDeclarationTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromLaterAssignments/getComponentAssignedTypesFromUsage.ts
- src/shared/FileInfoCache.ts
- src/shared/references.ts
There were previously two common ways in TypeStat fixers to find all references to a node: finding all the direct ts.ReferenceEntry instances, or a helpful wrapper around that to convert them to nodes. This PR switches everyone to using the helpful wrapper because there's no reason to want the direct reference entry otherwise.
Also seems to fix bugs around requesting source nodes from outside a particular position in a source file by using the referencing source file in lookup code here, rather than the original node's source file.
> Used findReferencesAsNodes instead of findReferences directly

- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromLaterAssignments/getComponentPropsNode.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/reactFiltering/isReactComponentNode.ts
When the props node doesn't have any declarations, getComponentPropsNode shouldn't bother trying to look through them.
I haven't filed bugs about this bug I remember there being crashes associated...
> Fixed miscellaneous bugs around React component signatures

- src/mutations/codeFixes/creation.ts
The text changes need to be checked for only containing parenthesis after known blank types are filtered out.
Fixes #278.
> Ignored implicit any fixes that are only parenthesis

- README.md
- docs/Architecture.md
- docs/Custom Mutators.md
- docs/Development.md
- docs/Files.md
- docs/Filters.md
- docs/Fixes.md
- docs/Package.md
- docs/Types.md
- docs/Usage.md
- src/cli/runCli.ts
- src/index.ts
- src/mutators/builtIn/fixIncompleteTypes/README.md
- src/mutators/builtIn/fixMissingProperties/README.md
- src/mutators/builtIn/fixNoImplicitAny/README.md
- src/mutators/builtIn/fixStrictNonNullAssertions/README.md
- src/options/fillOutRawOptions.ts
- src/options/findRawOptions.ts
- src/options/loadOptions.ts
- src/options/parsing/collectAddedMutators.ts
- src/options/parsing/collectFileOptions.ts
- src/options/parsing/collectNoImplicitAny.ts
- src/options/parsing/collectPackageOptions.ts
- src/options/parsing/collectStrictNullChecks.ts
- src/options/parsing/collectTypeAliases.ts
- src/tests/runTests.ts
Simplifies the CLI to not allow --filter, --fixNoImplicitAny, and other settings that are now recommended to be only set in a config file. This simplifies a lot of logic around parsing raw arguments.
Fixes #38.
> Removed CLI flags also included in config files

- src/runtime/providers/createCoreMutationsProvider.ts
It needs to be a log _after_ the services are created because if no file names are passed in options, services are required to get that count.
Fixes #220.
> Mentioned number of files being visited by language services

- src/mutations/codeFixes/creation.ts
- test/cases/unit/parameters/all/expected.ts
- test/cases/unit/parameters/default/expected.ts
- test/cases/unit/parameters/incompleteTypes/expected.ts
- test/cases/unit/parameters/noImplicitAny/expected.ts
- test/cases/unit/parameters/original.ts
- test/cases/unit/parameters/strictNonNullAssertions/expected.ts
Fixes #256.
We _could_ reverse the order of TypeScript codefixes... but that seems hacky.
> Accounted for adjacent TypeScript codefix starts

- src/mutations/codeFixes/processCodeFixActions.ts
Followup PR to #374. I was still seeing some symptoms of the original bug (#256) that was supposed to solve. Annoying!
As it turns out, when TypeScript proposed the following text changes:
* `"("`
* `": string"`
* `")"`
...then TypeStat was filtering out the first and last when `types.onlyPrimitives` was on, in an attempt to prevent complex types.
> Stopped filtering out non-alphanumeric text changes from TypeScript

- src/index.ts
- src/options/findRawOptions.ts
- src/options/loadOptions.ts
- src/options/optionVerification.ts
- src/options/processFileRenames.ts
Fixes #119.
This closes the loop on the changes around multi-step config generation introduced in #283. Configs are now stored as an array of options, which are then looped over in `typeStat`.
> Allowed an array of configurations in addition to just one

- src/mutations/codeFixes/extractRawCodefixUnionTypes.ts
- src/options/optionVerification.ts
- src/options/processFileRenames.ts
Fixes #243.
Directly adds a _"see (link) for details"_ to the extension rename complaint for JS files. I also noticed it was still referring to the old `--fileRenameExtensions` kind of CLI option setting that isn't supported anymore, so I fixed up the last few places I could find like that in code.
> Corrected '--' style links for docs

- src/mutators/builtIn/fixStrictNonNullAssertions/fixStrictNonNullAssertionCallExpressions/index.ts
- test/cases/fixes/missingProperties/missingPropertyAccesses/expected.ts
- test/cases/fixes/missingProperties/missingPropertyAccesses/original.ts
- test/cases/fixes/strictNonNullAssertions/callExpressions/expected.ts
- test/cases/fixes/strictNonNullAssertions/callExpressions/original.ts
-   [x] Addresses an existing issue: fixes #48
Checks if the parameter has the `any` flag set recursively, and skips creating the mutation if so.
> Don't add non-null assertions for any-typed parameters

- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteParameterTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompletePropertyDeclarationTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteVariableTypes/index.ts
- test/cases/fixes/incompleteTypes/parameterTypes/expected.ts
- test/cases/fixes/incompleteTypes/propertyDeclarationTypes/expected.ts
- test/cases/fixes/incompleteTypes/propertyDeclarationTypes/original.ts
- test/cases/fixes/incompleteTypes/variableTypes/expected.ts
- test/cases/fixes/noImplicitAny/variableDeclarations/expected.ts
- test/cases/types/onlyPrimitives/false/expected.ts
- test/cases/types/onlyPrimitives/true/expected.ts
-   [x] Addresses an existing issue: fixes #739
Adds an `isNodeWithType` check before fixing for incomplete property, parameter, and variable types.
> Stopped incompleteTypes fixer on type-less nodes

- src/mutations/collecting.ts
- src/mutations/creators.ts
- src/shared/nodeTypes.ts
- test/cases/fixes/incompleteTypes/variableTypes/expected.ts
- test/cases/fixes/incompleteTypes/variableTypes/original.ts
-   [x] Addresses an existing issue: fixes #257
Adds a hardcoding for `"Function"` as a name of an object in both collection and expansion: when hit, the original type will be ignored and replaced with more specific function type(s).
> Added type expansions for plain Functions

- src/mutations/expansions/addIncompleteTypesToType.ts
- src/mutations/expansions/eliminations.ts
- src/mutations/expansions/expansionMutations.ts
- src/shared/nodeTypes.ts
- test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromLaterAssignments/expected.tsx
- test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromLaterAssignments/original.tsx
-   [x] Addresses an existing issue: fixes #258
Copies (😦) some of the logic from `createTypeAdditionMutation` to `createTypeExpansionMutation`. Not super sure why both have organically grown but I don't see a quick & easy way to deduplicate... I guess this is ok for now.
> Added Function type expansion to React props

- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteInterfaceOrTypeLiteralGenerics/collectGenericNodeReferences.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompletePropertyDeclarationTypes/index.ts
- src/mutators/builtIn/fixMissingProperties/fixMissingPropertyAccesses/index.ts
-   [x] Addresses an existing issue: fixes #755; fixes #756
Applies two fixes for property declaration inferences:
* #755: filters them in `updateAssignedTypesForReference ` to only apply when the target being assigned is the same class being inferred for (the `.parent` of the property declaration `node`)
* #756: filters them in `fixMissingPropertyAccesses` to not apply when the node already has the same name declared
> Prevented duplicate TypeScript property inferences

- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteParameterTypes/index.ts
Disappointing that tests didn't cover this...
> Bugfix: missing callingTypes.push param in fixIncompleteParameterTypes

- src/mutations/aliasing/joinIntoType.ts
- src/mutations/assignments.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteInterfaceOrTypeLiteralGenerics/collectGenericNodeReferences.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropFunctionsFromCalls/collectAllFunctionCallTypes.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropFunctionsFromCalls/createFunctionCallTypesMutation.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropFunctionsFromCalls/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromLaterAssignments/getComponentAssignedTypesFromUsage.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/getComponentPropsNode.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/index.ts
- src/mutators/fileMutator.ts
- src/services/language.ts
- src/shared/comparisons.ts
- src/shared/nodeTypes.ts
- src/shared/typeNodes.ts
- src/shared/types.ts
- test/cases/fixes/incompleteTypes/reactTypes/fixReactPropFunctionsFromCalls/expected.tsx
- test/cases/fixes/incompleteTypes/reactTypes/fixReactPropFunctionsFromCalls/original.tsx
- test/cases/fixes/incompleteTypes/reactTypes/fixReactPropFunctionsFromCalls/tsconfig.json
- test/cases/fixes/incompleteTypes/reactTypes/fixReactPropFunctionsFromCalls/typestat.json
-   [x] Addresses an existing issue: fixes #766
Adds a React fixer for _specifically_ the `Function` types that tend to be output by other React fixers.
TypeScript unfortunately does not provide a good API for this (#761) so I made logic around `parameters` and `returnValue` options specifically for this fixer. Eventually it might make sense to generalize that, if more cases like this come up -- or even use `ts-simple-type`.
Adds a lazilly retrieved `wellKnownTypes: WellKnownTypes` to the language services. I ended up not using it here but it's nifty. 🤷
> Added Function usage inferences for React props

- src/cli/runCli.test.ts
- src/cli/runCli.ts
-   [x] Addresses an existing issue: fixes #774
```
All done! ✨
```
Also uses `expect.stringMatching` instead of `jasmine.stringMatching`. I'd learned about `expect` after first writing these tests... 😄
> Added 'all done' message on successful CLI completion

- src/index.ts
- src/options/loadOptions.ts
-   [x] Addresses an existing issue: fixes #796
If at least one path includes `node_modules`, but that wasn't explicitly in the include list, error.
> Error if node_modules is included by accident

- src/mutations/generics.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteImplicitGenerics/fixIncompleteImplicitVariableGenerics/createExplicitGenericType.ts
- test/cases/fixes/incompleteTypes/implicitGenerics/incompleteImplicitVariableGenerics/expected.ts
- test/cases/fixes/incompleteTypes/implicitGenerics/incompleteImplicitVariableGenerics/original.ts
-   [x] Addresses an existing issue: fixes #959
Two changes:
* Restricts printing to only happen when the existing inferred generic type doesn't contain later-added ones
* Fixes printing to properly treat generics such as maps as having a type name like `"Map"`, not `"Map<K, V>"`
> Fixed printing for incomplete implicit generics

- src/mutations/codeFixes/noImplicitAny.ts
- src/mutators/builtIn/fixStrictNonNullAssertions/fixStrictNonNullAssertionBinaryExpressions/index.ts
- src/mutators/builtIn/fixStrictNonNullAssertions/fixStrictNonNullAssertionPropertyAccesses/index.ts
- test/cases/fixes/strictNonNullAssertions/binaryExpressions/expected.ts
- test/cases/fixes/strictNonNullAssertions/binaryExpressions/original.ts
- test/cases/fixes/strictNonNullAssertions/propertyAccesses/expected.ts
- test/cases/fixes/strictNonNullAssertions/propertyAccesses/original.ts
-   [x] Addresses an existing issue: fixes #1019
Adds a couple of checks around binary expressions:
* Don't add `!` if the declared type is `any`
* Create a non-null assertion on the node expression, not the node itself
These changes were sitting on my local repo clone for two months. I'd completely forgotten about them until opening the repo with @beyang! 😂
> Don't add non null assertions to optional chaining

- src/options/getNewFileName.test.ts
- src/options/getNewFileName.ts
- src/options/processFileRenames.ts
- src/options/types.ts
-   [x] Addresses an existing issue: fixes #93
Adds a smarter heuristic for whether to switch to `.tsx`: checks for closing JSX tags, rather than importing `react`.
> Smarter regexp checking and unit tests for files.renameExtensions

- src/mutations/creators.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/propTypes/createInterfaceFromPropTypes.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsMissing.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/getApparentNameOfComponent.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/reactFiltering/isReactComponentNode.ts
- test/cases/fixes/incompleteTypes/reactTypes/reactPropsMissing/expected.tsx
- test/cases/fixes/incompleteTypes/reactTypes/reactPropsMissing/original.tsx
- test/cases/fixes/incompleteTypes/reactTypes/reactPropsMissing/tsconfig.json
- test/cases/fixes/incompleteTypes/reactTypes/reactPropsMissing/typestat.json
-   [x] Addresses an existing issue: fixes #1036
For a React component that doesn't have a `prop-types` `.propTypes` definition or an existing TypeScript props interface/type, creates a new one from scratch. It does so by finding each usage of the component and collecting named JSX element attributes & their types.
> Add fixer for React components with missing prop types

- src/mutators/builtIn/fixNoImplicitAny/README.md
-   [x] Addresses an existing issue: fixes #1043
Yay, docs!
> docs: correct typescript-eslint links to use typescript-eslint.io

- src/options/parseRawCompilerOptions.ts
-   [x] Addresses an existing issue: fixes #1060
Uses `glob.sync` instead of fancy file path concatenation. Simpler!
> fix: support TSConfig include globs

- src/mutations/creators.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompletePropertyDeclarationTypes/index.ts
- test/cases/fixes/incompleteTypes/propertyDeclarationTypes/expected.ts
- test/cases/fixes/incompleteTypes/propertyDeclarationTypes/original.ts
-   [x] Addresses an existing issue: fixes #1063
* `any`-typed properties are never incomplete, so the fixer should bail out early
* `never`- and `unknown`-typed properties are replaced altogether
> fix: account for bottom and top types in incompleteTypes unions

- src/initialization/initializeJavaScript/createJavaScriptConfig.test.ts
- src/initialization/initializeJavaScript/createJavaScriptConfig.ts
- src/initialization/initializeJavaScript/index.ts
- src/initialization/initializeProject/index.ts
- src/initialization/initializeProject/initializeNewProject.ts
- src/initialization/initializeProject/shared.ts
- src/initialization/initializeTypeScript/index.ts
- src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts
- src/initialization/initializeTypeScript/writeSingleTypeScriptConfig.ts
- src/initialization/sources/index.ts
-   [x] Addresses an existing issue: fixes #1003
The CLI now includes an option for `I don't have one yet` in the `Where is your tsconfig.json?` question. Under that option, it'll ask a few questions about compiler options.
`project` settings afterwards also now remember whether the project was created by this process, so after you select an include path, it'll add an `include` to that `tsconfig.json`.
```plaintext
✔ What are you trying to accomplish? · Convert my JavaScript files to TypeScript
✔ Where is your tsconfig.json? · I don't have one yet
✔ Should TypeScript output .js files from .ts sources? · yes
✔ Does your code run in browser? · yes
✔ Does …
```
> feat: create TSConfig in CLI

- src/initialization/initializeTypeScript/initializeTests.ts
- src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts
-   [x] Addresses an existing issue: fixes #1048
If the user does not have test files, he/she can skip the question `Which glob matches your test files?` with an option of `none`.
> 1048: added option for no tests

- src/index.ts
-   [x] Addresses an existing issue: fixes #1046
added: 
```
output.stdout(chalk.yellowBright("⚠️ TypeStat is still very early stage and experimental. ⚠️ While it will improve your code, it will likely add syntax and type errors. Use TypeStat as a starting point before you manually fix and verify any changes."))
```
> feat: print a disclaimer at the beginning of CLI runs

- src/mutations/creators.ts
- test/cases/fixes/incompleteTypes/parameterTypes/expected.ts
- test/cases/fixes/incompleteTypes/parameterTypes/original.ts
-   [x] Addresses an existing issue: fixes #1278
Adds logic to `createTypeAdditionMutation` to return no mutation if the declared type includes `any`.
> fix: don't expand existing type with explicit any

- src/initialization/index.ts
I believe this is what we need to run if typestat is not globally installed.
> Run typestat using npx

- src/cli/runCli.test.ts
- src/cli/runCli.ts
-   [x] Addresses an existing issue: fixes #1311
Adds an extra bit of logging if the rejected error is an `Error`.
> feat: log full error stacks on crash

- .github/DEVELOPMENT.md
- tsconfig.eslint.json
…eporting
Eslint has different result depending on if `lib`folder is present or not. When it is present, lint errors seems incorrect.
Excluding "lib" from eslint fixes the issue. Also, removed mention that you should build the project before linting. This is not done in CI and it seems unnecessary in current state. :)
> chore: set eslint to ignore lib folder

- src/mutations/collecting/flags.ts
- test/cases/fixes/incompleteTypes/returnTypes/expected.ts
- test/cases/fixes/incompleteTypes/returnTypes/original.ts
It was this small change in the end??
Note, `async function navigateTo(): Promise<boolean> | boolean {` and `async function navigateTo2(): Promise<boolean> | boolean {` are wrong. Both should return only `Promise<boolean>`. I can remove those from the test but I wanted to keep them to see, the difference.
> fix: No more adding infinite boolean for function returning promise

- .eslintrc.cjs
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteImplicitGenerics/collectTypeParameterReferences.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteImplicitGenerics/templateCollecting.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropFunctionsFromCalls/createFunctionCallTypesMutation.ts
Removes some unused arguments and enables lint rule for them
> chore: remove unused arguments

- src/mutations/codeFixes/addMissingProperty.ts
- src/mutations/codeFixes/noImplicitAny.ts
- src/mutations/collecting.ts
- src/mutations/creators.ts
- src/mutations/expansions/eliminations.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteImplicitGenerics/fixIncompleteImplicitClassGenerics/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteImplicitGenerics/fixIncompleteImplicitVariableGenerics/createExplicitGenericType.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompletePropertyDeclarationTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsMissing.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReturnTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteVariableTypes/index.ts
- src/mutators/builtIn/fixNoImplicitThis/index.ts
- src/mutators/builtIn/fixStrictNonNullAssertions/fixStrictNonNullAssertionBinaryExpressions/index.ts
- src/mutators/builtIn/fixStrictNonNullAssertions/fixStrictNonNullAssertionCallExpressions/index.ts
- src/shared/comparisons.ts
- src/shared/nodeExtensions.ts
- src/shared/nodes.ts
- src/shared/transforms.ts
- src/shared/types.ts
Let's use existing checks from `ts-api-utils` and `typescript` when they exists there. 
Priority is to use checks from Typescript first, and then from ts-api-utils. 
There was duplicated function, and I removed in same go: `getClassExtendsExpression` and `getClassExtendsType`. I can remove this change though and send it separately, but feels too trivial to have it's own task & PR :)
> chore: use ts-api-utils or typescript for symbol kind checks

- src/mutations/collecting.ts
Make the case for the void type
mutually exclusive with the other
check in the loop.
Suggested in https://github.com/JoshuaKGoldberg/TypeStat/pull/2025#discussion_r1864332874.
> fix: reduce work in loop

- .eslintrc.cjs
- docs/Custom Mutators.md
- docs/Package.md
- package.json
- pnpm-lock.yaml
Fix the casing of TypeStat in eslintrc, and add some ESLint suppressions for the blocks that trigger lint errors. This makes the new version of the plugin pass on the documentation.
> chore: fix eslint-plugin-markdown 5 update

- package.json
- pnpm-lock.yaml
Cherry-pick the vitest/coverage-v8 version 2.x update onto the vitest 2.x update branch. This fixes the error:
```
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
TypeError: this.resolveReporters is not a function
❯ V8CoverageProvider.initialize node_modules/.pnpm/@vitest+coverage-v8@1.6.0_vitest@2.1.6_@types+node@22.10.0_/node_modules/@vitest/coverage-v8/dist/provider.js:2233:22
❯ Vitest.initCoverageProvider node_modules/.pnpm/vitest@2.1.6_@types+node@22.10.0/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:10567:35
❯ Vitest.start node_modules/.pnpm/vitest@2.1.6_@types+node@22.10.0/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:10642:7
❯ startVitest node_modules/.pnpm/vitest@2.1.6_@types+node@22.10.0/node_modules/vitest/dist/chunks/cli-api.FAAw0S6C.js:11828:7
❯ start …
```
> chore: update to vitest 2.x

- .github/DEVELOPMENT.md
- .github/workflows/lint.yml
- bin/typestat.mjs
This is also noted in: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/e65eae3e00d797ce0d88b5a1eb9707c857c66944/.github/DEVELOPMENT.md?plain=1#L61
💖
> chore: remove unused disable-directive from linting after building

- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/annotation/createInterfaceUsageMutation.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsFromPropTypes/index.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReactTypes/fixReactPropsMissing.ts
- test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromPropTypes/all/expected.tsx
- test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromPropTypes/all/original.tsx
I think the checks are little bit late but I didn't find better place.
> fix: duplicate react props added

- src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.test.ts
- src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts
- src/initialization/initializeTypeScript/writeSingleTypeScriptConfig.test.ts
- src/initialization/initializeTypeScript/writeSingleTypeScriptConfig.ts
- Fixes issue where `null` was inserted to typestat.json `includes` list
- Fixes issue where option was `inferableTypes` when it should be `noInferableTypes`
- Added basic testing for config generation
For future:
- Config generation is still little bit broken. If I want to select just "Remove type annotations that don't change the meaning of code" option, the generated config file does not have it but instead has just `"incompleteTypes": true`.  -> Needs new issue created. 
🐙
> fix: writing TypeScript config file

- package.json
- pnpm-lock.yaml
- src/runtime/providers/createInstallMissingTypesProvider.ts
- src/runtime/providers/missingTypes/collectReferencedPackageNames.test.ts
- src/runtime/providers/missingTypes/collectReferencedPackageNames.ts
There is no need to use external package for this check, when we can use node's own `isBuiltin()` check. However, it needed minimum node version to be upgrade to `>=18.6`.
🐙
> fix: replace builtin-modules package with node's isBuiltin check

- src/initialization/initializeJavaScript/createJavaScriptConfig.test.ts
- src/initialization/initializeJavaScript/createJavaScriptConfig.ts
It seems that the structure should have `projectPath` instead of `project`. 
I also moved the code little bit so that there was less nested ternaries.
> fix: createJavaScriptConfig should print projectPath instead of project

- package.json
- pnpm-lock.yaml
- src/output/createProcessOutput.ts
`stripVTControlCharacters` was added in nodejs v16.11.0 and appears to be a direct replacement for the functionality from `strip-ansi`.
`TypeStat` already declares a dependency on nodejs >= 18 in its `package.json`, so depending on this new API should be safe.
Fixes #2177
> fix: replace `strip-ansi` with `stripVTControlCharacters`

- src/options/fillOutRawOptions.ts
- src/options/parsing/collectNoImplicitAny.ts
- src/options/parsing/collectNoImplicitThis.ts
- src/options/parsing/collectStrictNullChecks.ts
- test/__snapshots__/cleanups.test.ts.snap
I forgot this from #2192 , though maybe it's better to have it separately. 
This simplifies and IMO corrects the logic for some of these options. Before, it was possible that if you have `noImplicitAny` set as false in `typestat.json` file for the fixes, it would change the typescript compiler options to be also false. This could lead to weird behavior.
New logic set  `noImplicitAny`  as true in the collected compiler options if it's true either in the fixes section or in the original ts config file.
I think the `types` section in `BaseTypeStatOptions` is unnecessary. It's only used in `findComplaintForOptions` to check options and print "fixes.strictNonNullAssertions specified but not strictNullChecks." if there is mismatch. That check could use the actual collected compiler options. …
> fix: simplify collecting strict TS options

- src/mutations/collecting.ts
- src/mutations/creators.ts
- src/mutations/text-mutations.ts
- src/mutators/builtIn/fixIncompleteTypes/fixIncompleteReturnTypes/index.ts
- test/cases/fixes/incompleteTypes/returnTypes/expected.ts
- test/cases/fixes/incompleteTypes/returnTypes/original.ts
- test/fixIncompleteTypes.test.ts
Wrap inside Promise, if one of the existing types mentions Promise.
> fix: incompleteReturnTypes: async function can only return Promises

- src/mutations/codeFixes/creation.test.ts
- src/mutations/codeFixes/creation.ts
- test/cases/fixes/noImplicitAny/parameters/expected.ts
- test/cases/fixes/noImplicitAny/parameters/original.ts
I noticed that the test did not actually test previous issue anymore, because formatter had fixed the code and added parenthesis already. I also added unit test for `simplifyTextChanges`. I was fixing another issue and just noticed that I broke this code, but the tests were still passing happily.
> test: fix tests to actually test parameter wrapping
